# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CORe_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(893, 624)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background: #FAFAFA;\n"
"}\n"
"\n"
"#widget,  #widget_3, #widget_5{\n"
"background: #FFF;\n"
"border-radius: 15px;\n"
"\n"
"    color: #fff;\n"
"    font-size: 14px;\n"
"    font-family: Poppins;\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    line-height: 100%;\n"
"}\n"
"\n"
"#widget_2,  #widget_4, #frame{\n"
"background: #FFF;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"/* ---------------- Style for QPushButton---------------- */\n"
"\n"
"QPushButton{\n"
"    padding: 3px 7px;\n"
"    border-radius: 10px;\n"
"    background: #4368EB;\n"
"\n"
"    color: #fff;\n"
"    font-size: 14px;\n"
"    font-family: Poppins;\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    line-height: 100%;\n"
"}\n"
"QPushButton:hover{\n"
"    background:  rgba(67, 104, 235, 0.6);\n"
"}\n"
"\n"
"\n"
"/* ---------------- Style for QLineEdit---------------- */\n"
"\n"
"QLineEdit{\n"
"    padding: 2px 7px;\n"
"    \n"
"    border-radius: 5px;\n"
"    border: 1px solid #757575;\n"
"    background: #FFF;\n"
"    \n"
"    color: #1B1E20;\n"
"    font-weight: 500;\n"
"    line-height: 150%;\n"
"}\n"
"\n"
"QTextBrowser{\n"
"    padding: 11px 15px;\n"
"    \n"
"    border-radius: 5px;\n"
"    border: 1px solid #757575;\n"
"    background: #FFF;\n"
"    \n"
"    color: #1B1E20;\n"
"    font-weight: 500;\n"
"    line-height: 150%;\n"
"}\n"
"\n"
"\n"
"/* ---------------- Style for QComboBox ---------------- */\n"
"\n"
"\n"
"QComboBox {\n"
"    border-radius: 5px;\n"
"    border: 1px solid #757575;\n"
"    padding: 2px 5px;\n"
"\n"
"    color: #1B1E20;\n"
"    font-size: 14px;\n"
"    font-family: Poppins;\n"
"    font-weight: 500;\n"
"\n"
"    background-color: #FFF;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #FFF;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #757575;\n"
"    padding: 3px;\n"
"    color: #1B1E20;\n"
"    selection-background-color: #636a87;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"    background-color : #FFFFFF  ;\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background-color : #FFFFFF  ;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-left-width: 0px;\n"
"    border-left-style: solid; \n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icon/Arrow - Down -- Black.svg);\n"
"\n"
"    width: 16px; \n"
"    height: 16px;\n"
"    padding-right : 15px;\n"
"} \n"
"\n"
"\n"
"/* ---------------- Style for QSpinBox ---------------- */\n"
"\n"
"\n"
"QSpinBox {\n"
"    border-radius: 5px;\n"
"    border: 1px solid #757575;\n"
"    padding: 3px 15px;\n"
"\n"
"    color: #1B1E20;\n"
"    font-size: 14px;\n"
"    font-family: Poppins;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right; /* position at the top right corner */\n"
"\n"
"    image: url(:/icon/spin up -- Black.svg);\n"
"    border-width: 1px;\n"
"    padding : 10px 15px;\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right; /* position at bottom right corner */\n"
"\n"
"    image: url(:/icon/spin down -- Black.svg);\n"
"    border-width: 1;\n"
"    padding : 10px 15px;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.gridLayout_4.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.tab)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.get_sgRNAs_button = QtWidgets.QPushButton(self.widget_2)
        self.get_sgRNAs_button.setObjectName("get_sgRNAs_button")
        self.gridLayout.addWidget(self.get_sgRNAs_button, 3, 2, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.uniprot_id_line_edit = QtWidgets.QLineEdit(self.widget_2)
        self.uniprot_id_line_edit.setObjectName("uniprot_id_line_edit")
        self.gridLayout.addWidget(self.uniprot_id_line_edit, 1, 1, 1, 2)
        self.amino_acid_position_line_edit = QtWidgets.QLineEdit(self.widget_2)
        self.amino_acid_position_line_edit.setObjectName("amino_acid_position_line_edit")
        self.gridLayout.addWidget(self.amino_acid_position_line_edit, 1, 3, 1, 1)
        self.upload_reference_genome_button = QtWidgets.QPushButton(self.widget_2)
        self.upload_reference_genome_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.upload_reference_genome_button.setObjectName("upload_reference_genome_button")
        self.gridLayout.addWidget(self.upload_reference_genome_button, 0, 1, 1, 3)
        self.gRNA_distance_line_edit = QtWidgets.QLineEdit(self.widget_2)
        self.gRNA_distance_line_edit.setObjectName("gRNA_distance_line_edit")
        self.gridLayout.addWidget(self.gRNA_distance_line_edit, 3, 1, 1, 1)
        self.gridLayout_4.addWidget(self.widget_2, 1, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.tab)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.homology_arm_length_lineEdit = QtWidgets.QLineEdit(self.widget_4)
        self.homology_arm_length_lineEdit.setObjectName("homology_arm_length_lineEdit")
        self.gridLayout_2.addWidget(self.homology_arm_length_lineEdit, 0, 1, 1, 1)
        self.generate_hdr_template_button = QtWidgets.QPushButton(self.widget_4)
        self.generate_hdr_template_button.setObjectName("generate_hdr_template_button")
        self.gridLayout_2.addWidget(self.generate_hdr_template_button, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.generate_integration_specifc_primer_button = QtWidgets.QPushButton(self.widget_4)
        self.generate_integration_specifc_primer_button.setObjectName("generate_integration_specifc_primer_button")
        self.gridLayout_2.addWidget(self.generate_integration_specifc_primer_button, 1, 1, 1, 2)
        self.gridLayout_4.addWidget(self.widget_4, 2, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.gridLayout_4.addWidget(self.widget_5, 3, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setHorizontalSpacing(20)
        self.gridLayout_3.setVerticalSpacing(15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.hdr_library_table = QtWidgets.QTableWidget(self.frame)
        self.hdr_library_table.setObjectName("hdr_library_table")
        self.hdr_library_table.setColumnCount(0)
        self.hdr_library_table.setRowCount(0)
        self.gridLayout_3.addWidget(self.hdr_library_table, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.results_table = QtWidgets.QTableWidget(self.frame)
        self.results_table.setObjectName("results_table")
        self.results_table.setColumnCount(0)
        self.results_table.setRowCount(0)
        self.gridLayout_3.addWidget(self.results_table, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 4, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.tab)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.save_button = QtWidgets.QPushButton(self.widget_6)
        self.save_button.setMinimumSize(QtCore.QSize(80, 35))
        self.save_button.setMaximumSize(QtCore.QSize(85, 35))
        self.save_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_3.addWidget(self.save_button)
        self.reset_button = QtWidgets.QPushButton(self.widget_6)
        self.reset_button.setMinimumSize(QtCore.QSize(80, 35))
        self.reset_button.setMaximumSize(QtCore.QSize(85, 35))
        self.reset_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout_3.addWidget(self.reset_button)
        self.gridLayout_4.addWidget(self.widget_6, 5, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CRISPR-TAPE 2.0"))
        self.label.setText(_translate("MainWindow", "Welcome to CORe designer"))
        self.label_7.setText(_translate("MainWindow", "Input the Uniprot ID and residue position of your amino acid"))
        self.label_4.setText(_translate("MainWindow", "Please upload reference genome using the upload button"))
        self.get_sgRNAs_button.setText(_translate("MainWindow", "Generate guide RNAs"))
        self.label_12.setText(_translate("MainWindow", "Please specify the maximum distance from amino acid  for guides to be generated and click generate guide RNAs"))
        self.uniprot_id_line_edit.setText(_translate("MainWindow", "e.g. A0A075B6Q4"))
        self.amino_acid_position_line_edit.setText(_translate("MainWindow", "e.g. 50"))
        self.upload_reference_genome_button.setText(_translate("MainWindow", "Upload reference genome"))
        self.gRNA_distance_line_edit.setText(_translate("MainWindow", "e.g 100"))
        self.label_5.setText(_translate("MainWindow", "Please specify homology arm length and click generate homology directed repair (HDR) library"))
        self.homology_arm_length_lineEdit.setText(_translate("MainWindow", "e.g 100"))
        self.generate_hdr_template_button.setText(_translate("MainWindow", "Generate HDR library"))
        self.label_6.setText(_translate("MainWindow", "Generate integration specific primers"))
        self.generate_integration_specifc_primer_button.setText(_translate("MainWindow", "Generate integration specific primers"))
        self.label_11.setText(_translate("MainWindow", "Results will be updated as you run through the program"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Main Results</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">HDR library results</span></p></body></html>"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.reset_button.setText(_translate("MainWindow", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
